### ISSUE TITLE
Log rotation problem

### ISSUE THREAD

**Issue by burandobata** [hortonworks/registry#490]
Hi,

I have a problem with log rotation for application logs. I'm using following settings:
```
logging:
 level: INFO
 loggers:
  com.hortonworks.registry: INFO
 appenders:
   - type: file
     threshold: INFO
     logFormat: "%-6level [%d{yyyy-MM-dd HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
     currentLogFilename: /var/log/registry/registry.log
     archivedLogFilenamePattern: /var/log/registry/registry-%d{yyyy-MM-dd}-%i.log.gz
     archivedFileCount: 5
     maxFileSize: 128MB
```

Above settings will keep archived logs for last 5 days not last 5 files. If I have lot of queries I'm suffering from log flooding. 
When I've tried to change the line to:  ```archivedLogFilenamePattern: /var/log/registry/registry-%i.log.gz``` it doesn't log at all.

Is there a way to tweak configuration in order to use both: ```archivedFileCount``` and ```maxFileSize``` ?

**Comment by burandobata** [comment]
Hey,

I've tried exactly that and I don't have registry.log. It's not being created at all. I've cleared /var/log/registry/* but it hasn't helped as well.
Here is my new config(copy-pasted):
```
logging:

 # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
 level: INFO
 # Logger-specific levels.
 loggers:
  # Sets the level for 'com.example.app' to DEBUG.
  com.hortonworks.registry: INFO
 appenders:
   - type: file
     threshold: DEBUG
     logFormat: "%-6level [%d{yyyy-MM-dd HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
     currentLogFilename: /var/log/registry/registry.log
     archivedLogFilenamePattern: /var/log/registry/registry-%i.log.gz
     archivedFileCount: 3
     timeZone: UTC
     maxFileSize: 1MB
```

I've tried 0.5.1 from github release as well as 0.5.0 from HDF 3.1.2. They problem is the same for me.

thanks,
Marek
