### ISSUE TITLE
Remove outdated haConfig's from default yaml files 

### ISSUE THREAD

**Issue by snemuri** [hortonworks/registry#557]
Remove the outdated HD configs from default yaml files, The current HA implementation doesn't need these configs.

```
# HA configuration
# When no configuration is set, then all the nodes in schema registry cluster are eligible to write to the backend storage.
haConfig:
  className: com.hortonworks.registries.ha.zk.ZKLeadershipParticipant
  config:
    # This url is a list of ZK servers separated by ,
    connect.url: "localhost:2181"
    # root node prefix in ZK for this instance
    root: "/registry"
    session.timeout.ms: 30000
    connection.timeout.ms: 20000
    retry.limit: 5
    retry.base.sleep.time.ms: 1000
    retry.max.sleep.time.ms: 5000
```
