### ISSUE TITLE
Failed to add the foreign key constraint

### ISSUE THREAD

**Issue by Mlng-ZHang** [hortonworks/registry#563]
schema registry version:0.7.0
mysql version: 8.0

registry.yaml
```
# MySQL based jdbc provider configuration is:
storageProviderConfiguration:
 providerClass: "com.hortonworks.registries.storage.impl.jdbc.JdbcStorageManager"
 properties:
   db.type: "mysql"
   queryTimeoutInSecs: 30
   db.properties:
     dataSourceClassName: "com.mysql.cj.jdbc.MysqlDataSource"
     dataSource.url: "jdbc:mysql://localhost:3306/schema_registry?useSSL=false&useUnicode=true&characterEncoding=utf-8"
     dataSource.user: "root"
     dataSource.password: "abcd1234"
```

when i run Bootstrap script 
> ./bootstrap/bootstrap-storage.sh  create

```
Using Configuration file: ./bootstrap/../conf/registry.yaml
[main] INFO org.flywaydb.core.internal.util.VersionPrinter - Flyway Community Edition 5.1.4 by Boxfuse
[main] INFO org.flywaydb.core.internal.database.DatabaseFactory - Database: jdbc:mysql://localhost:3306/schema_registry (MySQL 8.0)
[main] INFO org.flywaydb.core.internal.command.DbValidate - Successfully validated 5 migrations (execution time 00:00.023s)
[main] INFO org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory - Creating Schema History table: `schema_registry`.`DATABASE_CHANGE_LOG`
[main] INFO org.flywaydb.core.internal.command.DbMigrate - Current version of schema `schema_registry`: << Empty Schema >>
[main] INFO org.flywaydb.core.internal.command.DbMigrate - Migrating schema `schema_registry` to version 001 - create tables
[main] WARN org.flywaydb.core.internal.database.ExecutableSqlScript - DB: Failed to add the foreign key constraint. Missing index for constraint 'schema_version_info_ibfk_1' in the referenced table 'schema_metadata_info' (SQL State: HY000 - Error Code: 1822)
[main] ERROR org.flywaydb.core.internal.command.DbMigrate - Migration of schema `schema_registry` to version 001 - create tables failed! Please restore backups and roll back database and code!
"create" option failed : org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration v001__create_tables.sql failed
----------------------------------------
SQL State  : HY000
Error Code : 1822
Message    : Failed to add the foreign key constraint. Missing index for constraint 'schema_version_info_ibfk_1' in the referenced table 'schema_metadata_info'
Location   : ./bootstrap/sql/mysql/v001__create_tables.sql (/opt/hortonworks-registry-0.7.0/./bootstrap/sql/mysql/v001__create_tables.sql)
Line       : 35
Statement  : CREATE TABLE IF NOT EXISTS schema_version_info (
  id               BIGINT AUTO_INCREMENT NOT NULL,
  description      TEXT,
  schemaText       TEXT                  NOT NULL,
  fingerprint      TEXT                  NOT NULL,
  version          INT                   NOT NULL,
  schemaMetadataId BIGINT                NOT NULL,
  timestamp        BIGINT                NOT NULL,
  name             VARCHAR(255)          NOT NULL,
  UNIQUE KEY (id),
  UNIQUE KEY `UK_METADATA_ID_VERSION_FK` (schemaMetadataId, version),
  PRIMARY KEY (name, version),
  KEY `schemaMetadataId` (`schemaMetadataId`,`name`),
  CONSTRAINT `schema_version_info_ibfk_1` FOREIGN KEY (`schemaMetadataId`, `name`) REFERENCES `schema_metadata_info` (`id`, `name`) ON DELETE CASCADE ON UPDATE CASCADE
)
```
